Project/SneakerC2C/SneakerC2C/Models/DonHang.cs
using System;
using System.Collections.Generic;

namespace SneakerC2C.Models
{
    public partial class DonHang
    {
        public DonHang()
        {
            ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }

        public Guid Id { get; set; }
        public string MaDonHang { get; set; }
        public Guid IdTaiKhoan { get; set; }
        public string DiaChiGiao { get; set; }
        public DateTime? NgayTao { get; set; }
        public double? TongTien { get; set; }
        public string TinhTrangDanhGiaCustomer { get; set; }
        public string TinhTrang { get; set; }

        public TaiKhoan IdTaiKhoanNavigation { get; set; }
        public ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
    }
}

Project/SneakerC2C/SneakerC2C/Areas/Customer/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.BusinessLogicLayer;
using Models.Database;

namespace SneakerC2C.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class DonHangController : BaseController
    {
        private GioHangBUS giohangbus = new GioHangBUS();
        private TaiKhoanBUS taikhoanbus = new TaiKhoanBUS();
        private GiaShipBUS giashipbus = new GiaShipBUS();
        private DonHangBUS donhangbus = new DonHangBUS();
        private HangSanPhamBUS hangsanphambus = new HangSanPhamBUS();

        public IActionResult DatHang(string tendangnhap)
        {
            string checktendangnhap = HttpContext.Session.GetString("TenDangNhap");
            if (checktendangnhap != null && checktendangnhap != "")
            {
                TaiKhoan taikhoan = new TaiKhoan();
                taikhoan = taikhoanbus.CheckTaiKhoan(tendangnhap);
                List<GioHang> list = giohangbus.GetGioHangs(tendangnhap);
                List<TaiKhoan> listmerchant = giohangbus.GetMerchants(tendangnhap);
                List<DiaChi> listaddress = taikhoanbus.GetAllAddress(tendangnhap);
                DiaChi firstAddress = taikhoanbus.GetFirstAddress(tendangnhap);
                List<HangSanPham> hang = hangsanphambus.GetHangSanPhams();

                ViewBag.Hang = hang;
                ViewBag.TaiKhoan = taikhoan;
                ViewBag.Merchants = listmerchant;
                ViewBag.FirstAddress = firstAddress;
                ViewBag.ListAddress = listaddress;

                return View(list);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GetPhiShip(string tendangnhap, string iddiachi)
        {
            string checktendangnhap = HttpContext.Session.GetString("TenDangNhap");
            if (checktendangnhap != null && checktendangnhap != "")
            {
                List<DiaChi> listdiachi = new List<DiaChi>();
                listdiachi = giohangbus.GetPhiShip(tendangnhap);

                DiaChi diachi = new DiaChi();
                diachi = taikhoanbus.GetChoosenAddress(iddiachi);

                List<GiaShip> listgiaship = new List<GiaShip>();
                listgiaship = giashipbus.GetGiaShips();

                ViewBag.GiaShipNoiThanh = listgiaship.Where(gs => gs.Loai.Contains("Nội Thành"))
                                                     .OrderByDescending(gs => gs.NgayCapNhat)
                                                     .FirstOrDefault();
                ViewBag.GiaShipNgoaiThanh = listgiaship.Where(gs => gs.Loai.Contains("Ngoại Thành"))
                                                       .OrderByDescending(gs => gs.NgayCapNhat)
                                                       .FirstOrDefault();
                ViewBag.DiaChi = diachi;
            
                return PartialView("pTienThanhToan", listdiachi);
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GetDiaChi(string tendangnhap, string iddiachi)
        {
            string checktendangnhap = HttpContext.Session.GetString("TenDangNhap");
            if (checktendangnhap != null && checktendangnhap != "")
            {
                DiaChi diachi = new DiaChi();
                diachi = taikhoanbus.GetChoosenAddress(iddiachi);

                TaiKhoan taikhoan = new TaiKhoan();
                taikhoan = taikhoanbus.CheckTaiKhoan(tendangnhap);
                ViewBag.TaiKhoan = taikhoan;

                return PartialView("pDiaChi", diachi);
            }
            return RedirectToAction("Index", "Home");
        }

        public string CheckDonHang(string tendangnhap)
        {
            string checktendangnhap = HttpContext.Session.GetString("TenDangNhap");
            if (checktendangnhap != null && checktendangnhap != "")
            {
                string thongbao = donhangbus.CheckDonHang(tendangnhap);
                return thongbao;
            }
            return "";
        }

        public void CreateDonDatHang(string tendangnhap, string iddiachi, double tongtien)
        {
            string checktendangnhap = HttpContext.Session.GetString("TenDangNhap");
            if (checktendangnhap != null && checktendangnhap != "")
            {
                donhangbus.CreateDonDatHang(tendangnhap, iddiachi, tongtien);
            }
        }
    }
}

Project/SneakerC2C/SneakerC2C/Areas/Merchant/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.BusinessLogicLayer;
using Models.Database;

namespace SneakerC2C.Areas.Merchant.Controllers
{
    [Area("Merchant")]
    public class DonHangController : BaseController
    {
        private readonly QLBanGiayContext ctx;
        public DonHangController(QLBanGiayContext context)
        {
            ctx = context;
        }
        public IActionResult Index(string thongbao)
        {
            //Thông báo
            if (thongbao != null)
            {
                ViewBag.ThongBao = thongbao;
            }
            return View();
        }

        public IActionResult ChoXuLy()
        {
            string tentk = HttpContext.Session.GetString("TenDangNhap");

            List<ChiTietDonHang> chitiet = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Chưa xử lý")
                                       .Include(s => s.IdDonHangNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                       .ToList();
            ViewBag.ChiTiet = chitiet;
            var tenmer = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Chưa xử lý")
                                        .Include(s => s.IdSizeSanPhamNavigation)
                                        .Select(s => s.IdDonHang)
                                        .Distinct()
                                        .ToList();
            List<DonHang> list = ctx.DonHang.Where(sp => tenmer.Contains(sp.Id)).Include(sp => sp.IdTaiKhoanNavigation).ToList();
            return View(list);
        }
        //chuyển qua để xử lý hàng
        public IActionResult XuLy(string iddonhang)
        {
            List<ChiTietDonHang> donhang = ctx.ChiTietDonHang.Where(s => s.IdDonHang == Guid.Parse(iddonhang) && s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap"))
                                            .Include(s => s.IdDonHangNavigation)
                                           .Include(s => s.IdSizeSanPhamNavigation)
                                           .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                           .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                            .ToList();
            foreach (var item in donhang)
            {
                item.TinhTrangChiTiet = "Chờ lấy hàng";
            }
            ctx.SaveChanges();
            return RedirectToAction("ChoLayHang");
        }
        public IActionResult Search_XL(string search)
        {
            List<DonHang> list = ctx.DonHang.Where(s => s.MaDonHang.ToString().Contains(search)).Include(s => s.IdTaiKhoanNavigation).ToList();
            return View("XuLy", list);
        }
        public IActionResult ChoLayHang()
        {
            string tentk = HttpContext.Session.GetString("TenDangNhap");

            List<ChiTietDonHang> chitiet = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Chờ lấy hàng")
                                        .Include(s => s.IdDonHangNavigation)
                                        .Include(s => s.IdSizeSanPhamNavigation)
                                        .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                        .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                        .ToList();
            ViewBag.ChiTiet = chitiet;
            var tenmer = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Chờ lấy hàng")
                                        .Include(s => s.IdSizeSanPhamNavigation)
                                        .Select(s => s.IdDonHang)
                                        .Distinct()
                                        .ToList();
            List<DonHang> list = ctx.DonHang.Where(sp => tenmer.Contains(sp.Id)).Include(sp => sp.IdTaiKhoanNavigation).ToList();
            return View(list);
        }
        public IActionResult Search_LH(string search)
        {
            List<DonHang> list = ctx.DonHang.Where(s => s.MaDonHang.ToString().Contains(search)).Include(s => s.IdTaiKhoanNavigation).ToList();
            return View("ChoLayHang", list);
        }
        //cap nhật giao hàng
        public IActionResult GiaoHang(string iddonhang)
        {
            List<ChiTietDonHang> donhang = ctx.ChiTietDonHang.Where(s => s.IdDonHang == Guid.Parse(iddonhang) && s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap"))
                                           .Include(s => s.IdDonHangNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                           .ToList();
            foreach (var item in donhang)
            {
                item.TinhTrangChiTiet = "Đang giao";
            }
            ctx.SaveChanges();
            return RedirectToAction("DangGiao");
        }
        public IActionResult Search_DG(string search)
        {
            List<DonHang> list = ctx.DonHang.Where(s => s.MaDonHang.ToString().Contains(search)).Include(s => s.IdTaiKhoanNavigation).ToList();
            return View("DangGiao", list);
        }
        public IActionResult DangGiao()
        {
            string tentk = HttpContext.Session.GetString("TenDangNhap");

            List<ChiTietDonHang> chitiet = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Đang giao")
                                       .Include(s => s.IdDonHangNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                       .ToList();
            ViewBag.ChiTiet = chitiet;
            var tenmer = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Đang giao")
                                        .Include(s => s.IdSizeSanPhamNavigation)
                                        .Select(s => s.IdDonHang)
                                        .Distinct()
                                        .ToList();
            List<DonHang> list = ctx.DonHang.Where(sp => tenmer.Contains(sp.Id)).Include(sp => sp.IdTaiKhoanNavigation).ToList();
            return View(list);
        }
        public IActionResult CapNhat(string iddonhang)
        {
            List<ChiTietDonHang> donhang = ctx.ChiTietDonHang.Where(s => s.IdDonHang == Guid.Parse(iddonhang) && s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap"))
                                           .Include(s => s.IdDonHangNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                          .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                           .ToList();
            foreach (var item in donhang)
            {
                item.TinhTrangChiTiet = "Đã xử lý";
                item.NgayGiao = DateTime.Now;
            }
            ctx.SaveChanges();
            return RedirectToAction("DaGiao");
        }
        public IActionResult DaGiao()
        {
            string tentk = HttpContext.Session.GetString("TenDangNhap");


            List<ChiTietDonHang> chitiet = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Đã xử lý")
                                       .Include(s => s.IdDonHangNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation)
                                       .Include(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                       .ToList();
            ViewBag.ChiTiet = chitiet;
            var tenmer = ctx.ChiTietDonHang.Where(s => s.IdSizeSanPhamNavigation.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.TinhTrangChiTiet == "Đã xử lý")
                                        .Include(s => s.IdSizeSanPhamNavigation)
                                        .Select(s => s.IdDonHang)
                                        .Distinct()
                                        .ToList();

Project/SneakerC2C/SneakerC2C/Areas/Merchant/Views/DonHang/ChoLayHang.cshtml
@model IEnumerable<Models.Database.DonHang>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ChoLayHang";
    Layout = "~/Views/Shared/_MerchantManagementLayout.cshtml";
}

<div class="container">
    <div class="customer_quanly">
        <div id="horizontalTab" style="width:100%">
            <ul class="resp-tabs-list menu" style="width:100%">
                <a asp-area="Merchant" asp-controller="DonHang" asp-action="ChoXuLy"><li>Chờ xử lý</li></a>
                <a asp-area="Merchant" asp-controller="DonHang" asp-action="ChoLayHang"><li style="background-color: #fc636b">Chờ lấy hàng</li></a>
                <a asp-area="Merchant" asp-controller="DonHang" asp-action="DangGiao"><li>Đang giao</li></a>
                <a asp-area="Merchant" asp-controller="DonHang" asp-action="DaGiao"> <li>Đã xử lý</li></a>
                <a asp-area="Merchant" asp-controller="DonHang" asp-action="DaHuy"><li>Đã Huỷ</li></a>
            </ul>
            <div class="col-md-5 header-middle fix_timkiem_merchant">
                <form asp-action="Search_LH" asp-controller="DonHang">
                    <input type="search" name="search" placeholder="Tìm kiếm..." required="">
                    <input type="submit" value=" ">
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="resp-tabs-container">
                <!--/tab_one-->
                @foreach (var item in Model)
                {
                    <div class="tab1">
                        <div class="form_donhang">
                            <div class="ql_donhang">
                                <div class="tenshop_donhang">
                                    <div class="sanpham_giohang">
                                        <a href="#">
                                            <i class="fa fa-user"></i>
                                            <h5>@item.IdTaiKhoanNavigation.TenDangNhap</h5>
                                        </a>
                                    </div>
                                    <div class="trangthai_donhang id_donhang">
                                        ID: @item.MaDonHang
                                    </div>
                                    <div class="trangthai_donhang id_donhang">Ngày đặt: @item.NgayTao</div>
                                </div>
                                <hr>
                                @{
                                    double tongtienhang = 0;
                                }
                                @foreach (var ct in ViewBag.ChiTiet)
                                {
                                    @if (ct.IdDonHangNavigation.MaDonHang == item.MaDonHang)
                                    {
                                        tongtienhang += ct.DonGia * ct.SoLuong;

                                        <div class="thongtin_donhang">
                                            <div class="sanpham_giohang sp_donhang">
                                                <div class="hinh_sanpham_giohang hinh_donhang" style="background-image:url(/Hinh/SanPham/@ct.IdSizeSanPhamNavigation.IdSanPhamNavigation.Hinh);"></div>
                                                <div class="form_ten_sp_giohang ten_sp_donban">
                                                    <h5>
                                                        @ct.IdSizeSanPhamNavigation.IdSanPhamNavigation.TenSanPham
                                                    </h5>
                                                </div>
                                                <div class="soluong_donban">
                                                    <h5>x @ct.SoLuong</h5>
                                                </div>
                                                <div class="donban_right">
                                                    <div class="tongtien_donban">
                                                        @ct.DonGia.ToString("#,###") đ
                                                        <h6>Thanh toán khi nhận hàng</h6>
                                                    </div>
                                                    <div class="trangthai_donban">
                                                        @ct.TinhTrangChiTiet
                                                        <h6>Để tránh việc giao hàng trễ,vui lòng giao hàng trước ngày mai.</h6>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                <hr>
                                <div class="chuthich_donban" style="display: flex;">
                                    <div class="tong_tien_mer">
                                        Tổng tiền hàng: @tongtienhang.ToString("#,###") đ
                                    </div>
                                    <div class="button_xuly_merchant">
                                        <a asp-controller="DonHang" asp-action="GiaoHang" asp-route-iddonhang="@item.Id" class="btn btn-info">Cập nhật giao hàng</a>
                                        <a asp-controller="DonHang" asp-action="GetChiTiet" asp-route-id="@item.Id" class="btn btn-danger btnChiTiet">Chi tiết</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

<!-- js -->
<script type="text/javascript" src="~/maintemplate/js/jquery-2.1.4.min.js"></script>
<!-- //js -->

<script src="~/maintemplate/js/modernizr.custom.js"></script>
<!-- Custom-JavaScript-File-Links -->
<!-- cart-js -->
<script src="~/maintemplate/js/minicart.min.js"></script>
<script>
    // Mini Cart
    paypal.minicart.render({
        action: '#'
    });

    if (~window.location.search.indexOf('reset=true')) {
        paypal.minicart.reset();
    }
</script>
<script src="~/maintemplate/js/easy-responsive-tabs.js"></script>
<script>
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion
            width: 'auto', //auto or any width like 600px
            fit: true,   // 100% fit in a container
            closed: 'accordion', // Start closed if in accordion view
            activate: function (event) { // Callback function if tab is switched
                var $tab = $(this);
                var $info = $('#tabInfo');
                var $name = $('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });
        $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
        });
    });
</script>
<!-- //script for responsive tabs -->
<!-- stats -->
<script src="~/maintemplate/js/jquery.waypoints.min.js"></script>
<script src="~/maintemplate/js/jquery.countup.js"></script>
<script>
    $('.counter').countUp();
</script>
<!-- //stats -->
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="~/maintemplate/js/move-top.js"></script>
<script type="text/javascript" src="~/maintemplate/js/jquery.easing.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
        });
    });
</script>
<!-- here stars scrolling icon -->
<script type="text/javascript">
    $(document).ready(function () {
        /*
            var defaults = {
            containerID: 'toTop', // fading element id
            containerHoverID: 'toTopHover', // fading element hover id
            scrollSpeed: 1200,
            easingType: 'linear'
            };
        */

        $().UItoTop({ easingType: 'easeOutQuart' });

    });
</script>
<!-- //here ends scrolling icon -->
<!-- for bootstrap working -->
<script type="text/javascript" src="~/maintemplate/js/bootstrap.js"></script>
@*<script>
        $(".btnChiTiet").click(function () {
            let id = $(this).closest(".tenshop_donhang").find(".trangthai_donhang id_donhang").val();
            $.ajax({
                url: "/Merchant/DonHang/GetChiTiet",
                type: "post",
                data: { "id": id },
                success: function (data) {
                    $("#modal-body-suachitiet").html(data);
                },
                error: function (data) {
                    alert("Error: " + data);
                }
            });
        });
    </script>*@