Project/SneakerC2C/SneakerC2C/Areas/Merchant/Controllers/QuanLyController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.BusinessLogicLayer;
using Models.Database;

namespace SneakerC2C.Areas.Merchant.Controllers
{
    [Area("Merchant")]
    public class QuanLyController : BaseController
    {
        const int pageSizeAll = 11;
        const int pageSize = 12;
        int pageNumber = 1;
        private readonly QLBanGiayContext ctx;
        public QuanLyController(QLBanGiayContext context)
        {
            ctx = context;
        }
        [HttpPost]
        public IActionResult InThongBao(SizeSanPham size)
        {
            string tentk = HttpContext.Session.GetString("TenDangNhap");

            List<SizeSanPham> test = ctx.SizeSanPham.Where(s => s.IdSanPhamNavigation.IdTaiKhoanNavigation.TenDangNhap == tentk && s.SoLuong == 0)
                                                    .Include(s=>s.IdSanPhamNavigation)
                                                    .Include(s=>s.IdSanPhamNavigation.IdTaiKhoanNavigation)
                                                    .ToList();

            //TempData["AlertMessage"] = message;

            //foreach (var item in test)
            //{
            //    message = "Sản phẩm" + item.IdSanPhamNavigation.TenSanPham + "đã hết size" + item.Size;
            //}
            return PartialView(test);
        }
        public IActionResult Index(string thongbao)
        {
            if (thongbao != null)
            {
                ViewBag.ThongBao = thongbao;
            }
            List<HangSanPham> hang = ctx.HangSanPham.ToList();
            ViewBag.HangSanPham = hang;
            
            //thongbao = "Sản phẩm" + item.IdSanPhamNavigation.TenSanPham + "đã hết size" + item.Size;
            //Thông báo

            return View();
        }
        public List<SanPham> Get()
        {
            List<SanPham> list= ctx.SanPham.Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap") && sp.TinhTrang == "Không khoá" && sp.IdTaiKhoanNavigation.ThoiHanGianHang>DateTime.Now)
                                           .Include(sp => sp.IdTaiKhoanNavigation)
                                           .Include(sp => sp.IdHangSanPhamNavigation)
                                           .ToList();
            return list;
        }
        public List<SanPham> Get(int pagenumber, int pagesize)
        {
            List<SanPham> list = ctx.SanPham.Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap") && sp.TinhTrang == "Không khoá" && sp.IdTaiKhoanNavigation.ThoiHanGianHang > DateTime.Now)
                                           .Include(sp => sp.IdTaiKhoanNavigation)
                                           .Include(sp => sp.IdHangSanPhamNavigation)
                                           .Skip((pagenumber - 1) * pagesize)
                                           .Take(pagesize)
                                           .ToList();
            return list;
        }
       
        public IActionResult ListSP(string thongbao, int? pagenumber)
        {
            //Thông báo
            if (thongbao != null)
            {
                ViewBag.ThongBaoList = thongbao;
            }

            pageNumber = pagenumber ?? 1;
            List<SizeSanPham> size = ctx.SizeSanPham.ToList();
            ViewBag.Size = size;
            List<SanPham> list = Get(pageNumber, pageSizeAll);
            List<SanPham> tong = Get();
            List<HangSanPham> hang = ctx.HangSanPham.ToList();
            ViewBag.TongTrang = TongTrang(tong);
            ViewBag.TrangHienTai = pageNumber;
            ViewBag.TrangThai = "index";
            ViewBag.HangSanPham = hang;
            //DateTime? date = ctx.SanPham.Where(t => t.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap")).Select(d => d.IdTaiKhoanNavigation.ThoiHanGianHang).SingleOrDefault();
            DateTime date = ctx.TaiKhoan.Where(tk => tk.TenDangNhap == HttpContext.Session.GetString("TenDangNhap")).Select(tk => tk.ThoiHanGianHang).SingleOrDefault() ?? DateTime.Now;
            ViewBag.Date = date;
            return View(list);
        }

        public List<SanPham> GetCD()
        {
            List<SanPham> list = ctx.SanPham.Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap"))
                                          .Where(sp => sp.TinhTrang == "Chưa duyệt")
                                           .Include(sp => sp.IdTaiKhoanNavigation)
                                          .Include(sp => sp.IdHangSanPhamNavigation)
                                          .ToList();
            return list;
        }
        public List<SanPham> GetCD(int pagenumber, int pagesize)
        {
            List<SanPham> list = ctx.SanPham.Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap"))
                                          .Where(sp => sp.TinhTrang == "Chưa duyệt")
                                           .Include(sp => sp.IdTaiKhoanNavigation)
                                          .Include(sp => sp.IdHangSanPhamNavigation)
                                           .Skip((pagenumber - 1) * pagesize)
                                           .Take(pagesize)
                                           .ToList();
            return list;
        }

        public IActionResult ChuaDuyetSP(int? pagenumber)
        {
            pageNumber = pagenumber ?? 1;
            List<SizeSanPham> size = ctx.SizeSanPham.ToList();
            ViewBag.Size = size;
            List<SanPham> list = GetCD(pageNumber, pageSizeAll);
            List<SanPham> tong = GetCD();
            List<HangSanPham> hang = ctx.HangSanPham.ToList();
            ViewBag.TongTrang = TongTrang(tong);
            ViewBag.TrangHienTai = pageNumber;
            ViewBag.TrangThai = "index";
            ViewBag.HangSanPham = hang;
            return View(list);
        }


        public IActionResult SearchCD(string search, int? pagenumber)
        {
            pageNumber = pagenumber ?? 1;
            List<SanPham> list = pSearchCD(search, pageSizeAll, pageNumber);
            List<SanPham> tong = pSearchCD(search, pageSizeAll);
            ViewBag.TrangHienTai = pageNumber;
            ViewBag.TongTrang = TongTrang(tong);
            ViewBag.TrangThai = "search";
            ViewBag.Search = search;
            return View("ChuaDuyetSP", list);
        }
        //search list sp all
        public List<SanPham> pSearchCD(string search, int pagesize, int pagenumber)
        {
            List<SanPham> list = new List<SanPham>();
            if (search == null)
            {
                list = GetCD(1, pagesize);
            }
            else
            {
                list = ctx.SanPham.Where(l => l.MaSanPham.Contains(search) ||
                                                   l.TenSanPham.Contains(search) ||
                                                   l.Mau.Contains(search))
                                       .Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap") && sp.TinhTrang == "Chưa duyệt")
                                       .Include(sp => sp.IdTaiKhoanNavigation)
                                           .Include(sp => sp.IdHangSanPhamNavigation)
                                       .Skip((pagenumber - 1) * pagesize)
                                       .Take(pagesize)
                                       .ToList();
            }
            return list;
        }
        //search list sp all
        public List<SanPham> pSearchCD(string search, int pagesize)
        {
            List<SanPham> list = new List<SanPham>();
            if (search == null)
            {
                list = GetCD(1, pagesize);
            }
            else
            {
                list = ctx.SanPham.Where(l => l.MaSanPham.Contains(search) ||
                                                   l.TenSanPham.Contains(search) ||
                                                   l.Mau.Contains(search))
                                       .Where(sp => sp.IdTaiKhoanNavigation.TenDangNhap == HttpContext.Session.GetString("TenDangNhap") && sp.TinhTrang == "Chưa duyệt")
                                       .Include(sp => sp.IdTaiKhoanNavigation)
                                        .Include(sp => sp.IdHangSanPhamNavigation)
                                       .ToList();
            }
            return list;
        }

        //search list sp all
        public IActionResult Search(string search, int? pagenumber)
        {
            pageNumber = pagenumber ?? 1;
            List<SanPham> list = pSearch(search, pageSizeAll, pageNumber);
            List<SanPham> tong =pSearch(search, pageSizeAll);
            ViewBag.TrangHienTai = pageNumber;
            ViewBag.TongTrang = TongTrang(tong);
            ViewBag.TrangThai = "search";
            ViewBag.Search = search;
            List<HangSanPham> hang = ctx.HangSanPham.ToList();
            ViewBag.HangSanPham = hang;
            return View("ListSP", list);
        }
        //search list sp all
        public List<SanPham> pSearch(string search, int pagesize, int pagenumber)
        {
            List<SanPham> list = new List<SanPham>();
            if (search == null)
            {
                list = Get(1, pagesize);
            }
            else
            {
                list = ctx.SanPham.Where(l => l.MaSanPham.Contains(search) ||
                                                   l.TenSanPham.Contains(search) ||
                                                   l.Mau.Contains(search))

Project/SneakerC2C/SneakerC2C/Areas/Merchant/Views/QuanLy/ChuaDuyetSP.cshtml
@model IEnumerable<Models.Database.SanPham>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ChuaDuyetSP";
    Layout = "~/Views/Shared/_MerchantManagementLayout.cshtml";
}

<div class="new_arrivals_agile_w3ls_info menu-qlsp">
    <div class="container">
        <div id="horizontalTab">
            <ul class="resp-tabs-list menu">
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ListSP"><li>Tất cả</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ConHang"><li>còn hàng</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="HetHang"><li>hết hàng</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="KhoaSP"><li>đã bị khoá</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ChuaDuyetSP"><li style="background-color: #fc636b">chưa duyệt</li></a>
            </ul>
            <div class="col-md-5 header-middle fix_timkiem_merchant">
                <form asp-action="SearchCD" asp-controller="QuanLy">
                    <input type="search" name="search" placeholder="Tìm kiếm..." required="">
                    <input type="submit" value=" ">
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="resp-tabs-container">
                <!--/tab_one-->
                <div class="tab1">
                    @{
                        int i = 0;
                    }
                    @foreach (var item in Model)
                    {
                        <div class="col-md-3 product-men margin_merchant">
                            <div class="men-pro-item simpleCart_shelfItem">
                                <div class="men-thumb-item">
                                    <div class="men-thumb-item">
                                        <input class="txtid-sanpham" type="text" hidden value="@item.Id" />
                                        <div class="anhsanpham-3" style="background-image: url(/Hinh/SanPham/@item.Hinh);"></div>
                                    </div>
                                </div>
                                <div class="item-info-product ">
                                    <h4><a href="single.html" class="tieude_sanpham">@item.TenSanPham</a></h4>
                                    <div class="info-product-price">
                                        @if (item.GiamGia != null && item.GiamGia != 0)
                                        {
                                            double gia = item.Gia * (100 - item.GiamGia) / 100 ?? 0;
                                            <p><span class="item_price">@gia.ToString("#,###") đ</span> <del>- @item.Gia.Value.ToString("#,###") đ</del></p>
                                        }
                                        else
                                        {
                                            <p><span class="item_price">@item.Gia.Value.ToString("#,###") đ</span></p>
                                        }
                                    </div>
                                    <div class="button-sua-xoa">
                                        <form>
                                            @*<input type="button" value="Sửa" class="button-sua" onclick="location.href='#'" />*@
                                            <input type="button" value="Xoá" class="button-xoa btnXoa" />
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        i++;
                        if (i % 4 == 0)
                        {
                            <div class="clearfix"></div>
                        }
                    }
                </div>
                <!--//tab_one-->
            </div>
        </div>
    </div>
    <div>
        <ul class="phantrang modal-1" style="padding-top: 1.5em;">
            @if (ViewBag.TrangHienTai == 1)
            {
                <li class="paginate_button page-item previous disabled" id="dataTable_previous">
                    <a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Trước</a>
                </li>
            }
            else
            {
                <li class="paginate_button page-item previous" id="dataTable_previous">
                    @switch (ViewBag.TrangThai)
                    {
                        case "index":
                            <a asp-controller="QuanLy" asp-action="ChuaDuyetSP" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai - 1)" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link pageNumber">Trước</a>
                            break;
                        case "search":
                            <a asp-controller="QuanLy" asp-action="SearchCD" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai - 1)" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link pageNumber">Trước</a>
                            break;
                    }
                </li>
            }
            @for (int k = 1; k <= ViewBag.TongTrang; k++)
            {
                if (k > 5)
                {
                    <li class="paginate_button page-item" disabled><a class="page-link" aria-controls="dataTable" data-dt-idx="0" tabindex="0" href="#">...</a></li>
                    <li class="paginate_button page-item">
                        @switch (ViewBag.TrangThai)
                        {
                            case "index":
                                <a asp-controller="QuanLy" asp-action="ChuaDuyetSP" asp-route-pagenumber="@Html.Raw(ViewBag.TongTrang)" class="pageNumber">@ViewBag.TongTrang</a>
                                break;

                            case "search":
                                <a asp-controller="QuanLy" asp-action="SearchCD" asp-route-pagenumber="@Html.Raw(ViewBag.TongTrang)" class="pageNumber">@ViewBag.TongTrang</a>
                                break;

                        }
                    </li>
                    break;
                }
                else
                {
                    if (k == ViewBag.TrangHienTai)
                    {
                        <li class="paginate_button page-item active"><a href="#" class="page-link" aria-controls="dataTable" data-dt-idx="2" tabindex="0">@k</a></li>
                    }
                    else
                    {
                        <li class="paginate_button page-item" aria-controls="dataTables-example" tabindex="0">
                            @switch (ViewBag.TrangThai)
                            {
                                case "index":
                                    <a asp-controller="QuanLy" asp-action="ChuaDuyetSP" asp-route-pagenumber="@k" class="page-link pageNumber" aria-controls="dataTable" data-dt-idx="3" tabindex="0">@i</a>
                                    break;
                                case "search":
                                    <a asp-controller="QuanLy" asp-action="SearchCD" asp-route-pagenumber="@k" class="page-link pageNumber" aria-controls="dataTable" data-dt-idx="3" tabindex="0">@i</a>
                                    break;
                            }
                        </li>
                    }
                }
            }
            @if (ViewBag.TrangHienTai == ViewBag.TongTrang)
            {
                <li class="paginate_button page-item next disabled" id="dataTable_next"><a class="page-link" aria-controls="dataTable" data-dt-idx="7" tabindex="0" href="#">Tiếp</a></li>
            }
            else
            {
                <li class="paginate_button page-item next" id="dataTable_next">
                    @switch (ViewBag.TrangThai)
                    {
                        case "index":
                            <a asp-controller="QuanLy" asp-action="ChuaDuyetSP" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai + 1)" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link pageNumber">Tiếp</a>
                            break;
                        case "search":
                            <a asp-controller="QuanLy" asp-action="SearchCD" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai + 1)" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link pageNumber">Tiếp</a>
                            break;
                    }
                </li>
            }
        </ul>
    </div>
</div>
<script type="text/javascript" src="~/maintemplate/js/jquery-2.1.4.min.js"></script>
<script>
   $(".pageNumber").click(function () {
        //Get addtional href
        let search = "@ViewBag.Search";
        //Href
        var $link = $('.pageNumber');
        var href = $link.attr('href').split('/');
        if (search != null && search != '') {
            href.push('&search=' + search); //here you set your new asp-route-pagenumber value
        }
        href = href.join('/');
        href = href.toString().replace(/\/&/g, '&');
        $link.attr('href', href);
    });
    @*$(".btnXoa").click(function () {
        let id = $(this).closest(".men-pro-item").find(".txtid-sanpham").val();
        $.ajax({
            url: "/Merchant/QuanLy/XoaSP",
            type: "post",
            data: { "id": id },
            success: function (data) {
                alert("Xoá thành công");
                window.location = "@Url.Action("ListSP", "QuanLy")";
            },
            error: function (data) {
                alert("Error: " + data);
            }
        });*@
    });
</script>

Project/SneakerC2C/SneakerC2C/Areas/Merchant/Views/QuanLy/ConHang.cshtml
@model IEnumerable<Models.Database.SanPham>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ConHang";
    Layout = "~/Views/Shared/_MerchantManagementLayout.cshtml";
}

<div class="new_arrivals_agile_w3ls_info menu-qlsp">
    <div class="container">
        <div id="horizontalTab">
            <ul class="resp-tabs-list menu">
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ListSP"><li>Tất cả</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ConHang"><li style="background-color: #fc636b">còn hàng</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="HetHang"><li>hết hàng</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="KhoaSP"><li>đã bị khoá</li></a>
                <a asp-area="Merchant" asp-controller="QuanLy" asp-action="ChuaDuyetSP"><li>chưa duyệt</li></a>
            </ul>
            <div class="col-md-5 header-middle fix_timkiem_merchant">
                <form asp-action="SearchCH" asp-controller="QuanLy">
                    <input type="search" name="search" placeholder="Tìm kiếm..." required="">
                    <input type="submit" value=" ">
                    <div class="clearfix"></div>
                </form>
            </div>
            <div class="resp-tabs-container">
                <!--/tab_one-->
                <div class="tab1">
                    @{
                        int i = 0;
                    }
                    @foreach (var item in Model)
                    {
                        <div class="col-md-3 product-men margin_merchant">
                            <div class="men-pro-item simpleCart_shelfItem">
                                <div class="men-thumb-item">
                                    <div class="men-thumb-item">
                                        <input class="txtid-sanpham" type="text" hidden value="@item.Id" />
                                        <div class="anhsanpham-3" style="background-image: url(/Hinh/SanPham/@item.Hinh);"></div>
                                    </div>
                                </div>
                                <div class="item-info-product ">
                                    <h4><a href="single.html" class="tieude_sanpham">@item.TenSanPham</a></h4>
                                    <div class="info-product-price">
                                        @if (item.GiamGia != null && item.GiamGia != 0)
                                        {
                                            double gia = item.Gia * (100 - item.GiamGia) / 100 ?? 0;
                                            <p><span class="item_price">@gia.ToString("#,###") đ</span> <del>- @item.Gia.Value.ToString("#,###") đ</del></p>
                                        }
                                        else
                                        {
                                            <p><span class="item_price">@item.Gia.Value.ToString("#,###") đ</span></p>
                                        }
                                    </div>
                                    <div class="button-sua-xoa">
                                        <form>
                                            <button class="button-sua btnSuaChiTiet" type="button" data-toggle="modal" data-target="#suaModal">Sửa</button>
                                            <input type="button" value="Xoá" class="button-xoa btnXoa" />
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        i++;
                        if (i % 4 == 0)
                        {
                            <div class="clearfix"></div>
                        }
                    }
                </div>
                <!--//tab_one-->

            </div>

        </div>
    </div>
    <div>
        <ul class="phantrang modal-1" style="padding-top: 1.5em;">
            @if (ViewBag.TrangHienTai == 1)
            {
                <li class="paginate_button page-item previous disabled" id="dataTable_previous">
                    <a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Trước</a>
                </li>
            }
            else
            {
                <li class="paginate_button page-item previous" id="dataTable_previous">
                    @switch (ViewBag.TrangThai)
                    {
                        case "index":
                            <a asp-controller="QuanLy" asp-action="ConHang" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai - 1)" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link pageNumber">Trước</a>
                            break;
                        case "search":
                            <a asp-controller="QuanLy" asp-action="SearchCH" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai - 1)" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link pageNumber">Trước</a>
                            break;
                    }
                </li>
            }
            @for (int k = 1; k <= ViewBag.TongTrang; k++)
            {
                if (k > 5)
                {
                    <li class="paginate_button page-item" disabled><a class="page-link" aria-controls="dataTable" data-dt-idx="0" tabindex="0" href="#">...</a></li>
                    <li class="paginate_button page-item">
                        @switch (ViewBag.TrangThai)
                        {
                            case "index":
                                <a asp-controller="QuanLy" asp-action="ConHang" asp-route-pagenumber="@Html.Raw(ViewBag.TongTrang)" class="pageNumber">@ViewBag.TongTrang</a>
                                break;

                            case "search":
                                <a asp-controller="QuanLy" asp-action="SearchCH" asp-route-pagenumber="@Html.Raw(ViewBag.TongTrang)" class="pageNumber">@ViewBag.TongTrang</a>
                                break;

                        }
                    </li>
                    break;
                }
                else
                {
                    if (k == ViewBag.TrangHienTai)
                    {
                        <li class="paginate_button page-item active"><a href="#" class="page-link" aria-controls="dataTable" data-dt-idx="2" tabindex="0">@k</a></li>
                    }
                    else
                    {
                        <li class="paginate_button page-item" aria-controls="dataTables-example" tabindex="0">
                            @switch (ViewBag.TrangThai)
                            {
                                case "index":
                                    <a asp-controller="QuanLy" asp-action="ConHang" asp-route-pagenumber="@k" class="page-link pageNumber" aria-controls="dataTable" data-dt-idx="3" tabindex="0">@k</a>
                                    break;
                                case "search":
                                    <a asp-controller="QuanLy" asp-action="SearchCH" asp-route-pagenumber="@k" class="page-link pageNumber" aria-controls="dataTable" data-dt-idx="3" tabindex="0">@k</a>
                                    break;
                            }
                        </li>
                    }
                }
            }
            @if (ViewBag.TrangHienTai == ViewBag.TongTrang)
            {
                <li class="paginate_button page-item next disabled" id="dataTable_next"><a class="page-link" aria-controls="dataTable" data-dt-idx="7" tabindex="0" href="#">Tiếp</a></li>
            }
            else
            {
                <li class="paginate_button page-item next" id="dataTable_next">
                    @switch (ViewBag.TrangThai)
                    {
                        case "index":
                            <a asp-controller="QuanLy" asp-action="ConHang" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai + 1)" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link pageNumber">Tiếp</a>
                            break;
                        case "search":
                            <a asp-controller="QuanLy" asp-action="SearchCH" asp-route-pagenumber="@Html.Raw(ViewBag.TrangHienTai + 1)" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link pageNumber">Tiếp</a>
                            break;
                    }
                </li>
            }
        </ul>
    </div>
</div>
<div class="modal fade" id="suaModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <form asp-controller="QuanLy" asp-action="EditSP" enctype="multipart/form-data" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Sản phẩm</h4>
                </div>
                <div class="modal-body" id="modal-body-suachitiet">

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-warning" id="btnSua">Sửa</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript" src="~/maintemplate/js/jquery-2.1.4.min.js"></script>
<script>
    $(".pageNumber").click(function () {
        //Get addtional href
        let search = "@ViewBag.Search";
        //Href
        var $link = $('.pageNumber');
        var href = $link.attr('href').split('/');
        if (search != null && search != '') {
            href.push('&search=' + search); //here you set your new asp-route-pagenumber value
        }
        href = href.join('/');
        href = href.toString().replace(/\/&/g, '&');
        $link.attr('href', href);
    });
    $(".btnSuaChiTiet").click(function () {
        let id = $(this).closest(".men-pro-item").find(".txtid-sanpham").val();
        $.ajax({
            url: "/Merchant/QuanLy/GetProductDetails",
            type: "post",
            data: { "id": id },
            success: function (data) {
                $("#modal-body-suachitiet").html(data);
            },
            error: function (data) {
                alert("Error: " + data);
            }
        });
    });
    $(".btnXoa").click(function () {
        let id = $(this).closest(".men-pro-item").find(".txtid-sanpham").val();
        $.ajax({
            url: "/Merchant/QuanLy/XoaSP",
            type: "post",
            data: { "id": id },
            success: function (data) {
                alert("Xoá thành công");
                window.location = "@Url.Action("ListSP", "QuanLy")";
            },
            error: function (data) {
                alert("Error: " + data);
            }
        });
    });
</script>

Project/SneakerC2C/SneakerC2C/Areas/Merchant/Views/QuanLy/HoTro.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "HoTro";
    Layout = "~/Views/Shared/_MerchantManagementLayout.cshtml";
}

<div class="container tt_trogiup">
    <h2>Chào Mừng Bạn Đến Với Trung Tâm Trợ Giúp Người Bán</h2>
    <br>
    <h4>Các câu hỏi thường gặp:</h4>
    <div class="txt_tt_trogiup">
        <a asp-area="Merchant" asp-controller="QuanLy" asp-action="HoTroTaoSanPham">Đăng 1 sản phẩm mới như thế nào?</a>
    </div>
    <div class="txt_tt_trogiup">
        <a asp-area="Merchant" asp-controller="QuanLy" asp-action="HoTroXoaSanPham">Vì sao sản phẩm của Shop tôi bị khóa hoặc bị xóa?</a>
    </div>
</div>